### ISSUE TITLE
General :: top-padding

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#18]
según el archivo de diseño arriba solo hay un padding de 25px, ahorita tenemos 100px.
<img width="517" alt="screen shot 2016-04-30 at 10 00 52 am" src="https://cloud.githubusercontent.com/assets/7799215/14936773/87707500-0eba-11e6-92fe-5c685354c932.png">

**Comment by alex-romanov** [comment]
corregido a 50px (que es lo que el archivo de diseño indica)
