### ISSUE TITLE
Menu - padding

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#19]
El menú en el diseño tiene un ancho de 100px, ahorita tenemos como 150

<img width="527" alt="screen shot 2016-04-30 at 10 03 44 am" src="https://cloud.githubusercontent.com/assets/7799215/14936798/e82b0e3c-0eba-11e6-9e48-cab7ccb69e0e.png">

**Comment by alex-romanov** [comment]
Querrás decir "alto", el menu tiene un padding de 50px  mas el alto de las letras= 113px, ya lo dejé asi.
