### ISSUE TITLE
inicio :: altura banner

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#20]
En el diseño marcan altura de 619px, comentaste no usar alturas fijas, pero en este caso si no se usa altura fija entonces tendriamos que hacer más chica la imagen para que se vea como quieren?

Ahorita por ej en mi resolución width: 1439 se ve así (el venadito cortado)
<img width="1015" alt="screen shot 2016-04-30 at 10 09 47 am" src="https://cloud.githubusercontent.com/assets/7799215/14936829/bc822a9e-0ebb-11e6-8c16-1a0bbfb0b1ab.png">

ahorita tienes height: 500px, supongo puedes mover este valor a 619?

**Comment by alex-romanov** [comment]
previamente tenía una altura fija de 500, se la subí a 619, pero creo que es posible que en tu resolución siga viéndose incompleta
