### ISSUE TITLE
inicio :: compromiso

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#21]
va más ancho el elemento, en el diseño tenemos 3 renglones, supongo que puedes pasarte a sm-10
<img width="734" alt="screen shot 2016-04-30 at 10 12 32 am" src="https://cloud.githubusercontent.com/assets/7799215/14936851/420627ba-0ebc-11e6-8ee8-8a72d17444c0.png">

**Comment by alex-romanov** [comment]
listo
