### ISSUE TITLE
inicio ::  showroom

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#22]
Va más espacio entre línea, un poco más espacio entre el botón y la parte de abajo (25px más).

También más anchas las líneas para que "showroom" salga en la primer línea.

Le puedes meter letter-spacing?

<img width="591" alt="screen shot 2016-04-30 at 10 18 13 am" src="https://cloud.githubusercontent.com/assets/7799215/14936888/2ff8fb14-0ebd-11e6-9e1b-7d336862bc33.png">

**Comment by alex-romanov** [comment]
listo
