### ISSUE TITLE
General :: footer height

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#23]
Podemos hacer el footer menos alto? en el diseno tiene 400px, ahorita tenemos mas de 500px, lo puedes reducir un poco?

**Comment by alex-romanov** [comment]
quedó de 414, respetando todos los margenes marcados.
Cabe mencionar que la imagen del logo que estaba en sprites era mucho más grande que la del diseño. Corregí eso y también se hizo más pequeña la del header (pero así debe de ser de acuerdo con el diseño).
