### ISSUE TITLE
nosotros :: quienes somos

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#25]
ahorita el texto esta en col-xs-12 col-sm-8 col-sm-offset-2, si le metes un row hacemos que el texto quede en 4 lineas

<col-xs-12 col-sm-8 col-sm-offset-2>
<row>
...
</row>
</col>
<img width="716" alt="screen shot 2016-04-30 at 11 44 15 am" src="https://cloud.githubusercontent.com/assets/7799215/14937307/f8317fba-0ec8-11e6-91aa-afdb23db1f1f.png">

**Comment by alex-romanov** [comment]
what?

**Comment by garciadiazjaime** [comment]
en el diseno son 4 renglones, ahorita son 5 ... lo que sugeria era meterle <row> para tener el margin -15px y asi lograr los 4 renglones

**Comment by alex-romanov** [comment]
como ves si mejor le bajo el letter-spacing a 1px
