### ISSUE TITLE
productos :: slider - textos

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#27]
No se está mostrando el título, su clase pinta el font de blanco, pero igual tiene problemas de alineación.

Los párrafos los puedes hacer menos anchos?

<img width="454" alt="screen shot 2016-04-30 at 11 47 24 am" src="https://cloud.githubusercontent.com/assets/7799215/14937328/bb99967c-0ec9-11e6-8750-6b4e5e74955d.png">

**Comment by alex-romanov** [comment]
![screen shot 2016-05-03 at 8 04 23 pm](https://cloud.githubusercontent.com/assets/5589437/15004298/48e97e6e-116a-11e6-81db-47f369c184f5.png)

Yo si veo el tíutulo.

Que tanto más anchos? ahorita tienen el ancho que el diseño.
