### ISSUE TITLE
productos :: slider - no-repeat

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#28]
Le falta a la img de fondo 'no-repeat', pues ahorita se esta repitiendo
<img width="278" alt="screen shot 2016-04-30 at 11 52 20 am" src="https://cloud.githubusercontent.com/assets/7799215/14937334/03bb9e1e-0eca-11e6-92e0-afa7cd5a9731.png">

**Comment by alex-romanov** [comment]
Originalmente lleva background-size: cover que evita también que se repita, nomás que decía 'background-sixe' ya lo corregí so no more prob.
