### ISSUE TITLE
productos :: showroom

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#30]
el texto "showroom deberia empezar en misma vertical que el slider de arriba, podemos ajustarlo?
<img width="647" alt="screen shot 2016-04-30 at 11 57 36 am" src="https://cloud.githubusercontent.com/assets/7799215/14937364/cf02485c-0eca-11e6-9be1-427fbd974134.png">

**Comment by alex-romanov** [comment]
done
