### ISSUE TITLE
services :: banner

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#31]
tanto titulo como texto va en dos líneas, se puede ajustar?
<img width="863" alt="screen shot 2016-04-30 at 11 58 59 am" src="https://cloud.githubusercontent.com/assets/7799215/14937369/fe39dbda-0eca-11e6-898a-d79830a3214d.png">

**Comment by alex-romanov** [comment]
Lo ajuste a que el texto esté en dos líneas, para ajustar bien a como está el diseño o se tiene que meter un <br /> a data en el título o hacer un bloque diferente con dos divs, your choice.
