### ISSUE TITLE
contacto :: ver mapa

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#32]
podemos quitarle el hover al "btn" ?
y meter letter-spacing?

<img width="311" alt="screen shot 2016-04-30 at 12 01 27 pm" src="https://cloud.githubusercontent.com/assets/7799215/14937383/53630dfc-0ecb-11e6-9e83-28059f2eeefe.png">

**Comment by alex-romanov** [comment]
El hover está indicado por pool, 
also, en movil los hovers de todos modos no se activan

other than that is all done.
