### ISSUE TITLE
contacto :: textos eje y

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#34]
tanto título como textos comienzan en mismo eje Y
<img width="415" alt="screen shot 2016-04-30 at 12 07 20 pm" src="https://cloud.githubusercontent.com/assets/7799215/14937425/46ec6a22-0ecc-11e6-9420-2efe09cdcfac.png">

**Comment by alex-romanov** [comment]
y como debe de ser?

**Comment by garciadiazjaime** [comment]
el icono del mapa va sobre el mismo eje Y que donde empieza 'informacion de contacto' ahorita tienes el texto y no el icono del mapa en ese eje Y

**Comment by alex-romanov** [comment]
arre, done
