### ISSUE TITLE
contacto :: eje y (ubicacion)

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#35]
Los 4 elementos: titulo, parrafo, campos, btn comienzan en mismo eje

<img width="543" alt="screen shot 2016-04-30 at 12 12 14 pm" src="https://cloud.githubusercontent.com/assets/7799215/14937436/e3aab8e6-0ecc-11e6-9073-4b1b3d85d485.png">

creo que los labels pueden ser col-xs-2, en lugar de col-xs-3, no? ahorita para escribir en el "input" hay que atinarle pues quedó muy a la derecha

**Comment by alex-romanov** [comment]
listo
