### ISSUE TITLE
rd :: inicio :: showroom

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#37]
Se encima un poco el botón de ubicación  con footer
<img width="371" alt="screen shot 2016-04-30 at 8 48 06 pm" src="https://cloud.githubusercontent.com/assets/7799215/14944017/e3dc5fa4-0fad-11e6-91fa-de5c5d0b222b.png">

**Comment by alex-romanov** [comment]
listo
