### ISSUE TITLE
rd :: footer :: logo

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#38]
ver si podemos hacer que el logo salga centrado
<img width="416" alt="screen shot 2016-05-01 at 3 03 57 pm" src="https://cloud.githubusercontent.com/assets/7799215/14944025/fab29612-0fad-11e6-8a9d-28e5b8866563.png">

**Comment by alex-romanov** [comment]
todo eso es una imagen y un sprite, hay que hacer otro sprite para responsive.
