### ISSUE TITLE
rd :: nosotros :: banner

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#39]
quizás hacer un poco más chica la letra para que no se corte?
<img width="389" alt="screen shot 2016-05-01 at 3 05 40 pm" src="https://cloud.githubusercontent.com/assets/7799215/14944038/37ffe5d8-0fae-11e6-902c-8772c9764a1d.png">

**Comment by alex-romanov** [comment]
listo
