### ISSUE TITLE
rd :: nosotros :: mobiliario

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#40]
hacer más chica el font-size para que no se corte?
<img width="390" alt="screen shot 2016-05-01 at 3 06 19 pm" src="https://cloud.githubusercontent.com/assets/7799215/14944045/54e5ed6e-0fae-11e6-86a5-d4d7d2b85ae5.png">

**Comment by alex-romanov** [comment]
listo
