### ISSUE TITLE
rd :: productos :: sliders

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#42]
podemos quitarle el fondo a los arrows? y quizás pegarlas a las orillas? ahorita esta medio raro el element.
<img width="443" alt="screen shot 2016-05-01 at 3 10 04 pm" src="https://cloud.githubusercontent.com/assets/7799215/14944069/e57861cc-0fae-11e6-9cc4-a46f295af394.png">

**Comment by alex-romanov** [comment]
done
