### ISSUE TITLE
Menu :: hover

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#46]
Cambiar el color del hover en la letra del menu principal,  se muestra rosa debe ser dorado.  

<img width="245" alt="screen shot 2016-05-05 at 10 11 39 pm" src="https://cloud.githubusercontent.com/assets/7799215/15063275/51fc65e8-130e-11e6-92b3-94584643281e.png">

**Comment by alex-romanov** [comment]
done
