### ISSUE TITLE
inicio :: block1 :: slider

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#47]
Activar flechas de navegación

Pool menciona:
"Sobre este mismo banner, nos gustaria que la imagen creciera desde el centro, ahorita crece desde la izquierda-arriba y se cortan muchos elementos de la parte de abajo en pantallas grandes,  podemos hacer que crezca desde el centro para evitar que corten tantos elementos."
se puede hacer algo?

**Comment by alex-romanov** [comment]
done
