### ISSUE TITLE
servicios :: banner

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#49]
mismo comentario que en inicio

"Sobre este mismo banner, nos gustaria que la imagen creciera desde el centro, ahorita crece desde la izquierda-arriba y se cortan muchos elementos de la parte de abajo en pantallas grandes,  podemos hacer que crezca desde el centro para evitar que corten tantos elementos. "

"eliminar la accion en las dos flechas hacia abajo en los banners" (que ya no sean link)

**Comment by alex-romanov** [comment]
done
