### ISSUE TITLE
productos :: slider

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#50]
Lo que quiere pool es que la img tenga un maximos (height, width) definidos.

pool menciona:
"hacer que imagen quede fija ( no crezca)
En el banner de productos en donde estan las colecciones con los animales, podemos hacer que esas imagenes no crezcan al escalar el navegador, quedando en el tamaño máximo definido, centradas horizontalmente. 

Esto para evitar que se pierdan elementos y se cambie la posicion de texto-imagen y se logre leer lo mejor posible.  
"
<img width="712" alt="screen shot 2016-05-05 at 10 19 48 pm" src="https://cloud.githubusercontent.com/assets/7799215/15063388/76ac2efe-130f-11e6-8762-b3efaa3a31a3.png">

https://basecamp.com/1879563/projects/12030021/todos/250404655

**Comment by alex-romanov** [comment]
done
