### ISSUE TITLE
nosotros :: quienes somos

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#51]
"Corregir la fuente del texto de QUIENES SOMOS, es el unico que se muestra con otra tipografia.  debe quedar igual al parrafo de nuestro compromiso.  "

<img width="703" alt="screen shot 2016-05-05 at 10 21 34 pm" src="https://cloud.githubusercontent.com/assets/7799215/15063407/b3c7d022-130f-11e6-9cc4-fecbe7fd6c0e.png">

https://basecamp.com/1879563/projects/12030021/todos/250405173

**Comment by alex-romanov** [comment]
done
