### ISSUE TITLE
general :: fb logo

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#53]
hacerlo más parecido:

<img width="50" alt="screen shot 2016-05-05 at 10 23 58 pm" src="https://cloud.githubusercontent.com/assets/7799215/15063455/10aa81ae-1310-11e6-819c-406440ea947e.png">

"solo un poco más vivo el azul y la f más chica"

**Comment by alex-romanov** [comment]
done
