### ISSUE TITLE
rd :: general :: menu

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#54]
Podemos ajustar el diseño del drop down,  elimnar la linea blanca que queda abajo y  centrar el texto  y  dar el doble de espacio entre renglones. ?

![screen shot 2016-05-06 at 4 22 38 pm](https://cloud.githubusercontent.com/assets/7799215/15086485/c977004a-13a6-11e6-976a-ad224be6faff.png)

https://basecamp.com/1879563/projects/12030021/todos/250792664

**Comment by alex-romanov** [comment]
done
