### ISSUE TITLE
RD :: home :: slider

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#57]
Las flechas se ven al cargar la pagina, pero al hacer scroll desaparecen
![screen shot 2016-05-23 at 8 44 58 pm](https://cloud.githubusercontent.com/assets/7799215/15489647/4e3eb9e8-2127-11e6-8ccf-f0f2ce05050e.png)

**Comment by alex-romanov** [comment]
done

**Comment by garciadiazjaime** [comment]
ahora ya no se ven
<img width="446" alt="screen shot 2016-05-25 at 1 47 03 pm" src="https://cloud.githubusercontent.com/assets/7799215/15552258/33e12d5c-227f-11e6-8fbc-97553b02b60e.png">

**Comment by alex-romanov** [comment]
Done
