### ISSUE TITLE
general :: acentos

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#58]
revisar acentos

**Comment by alex-romanov** [comment]
De cuando a acá esa es chamba de nosotros?

**Comment by garciadiazjaime** [comment]
sabes si es porque nos hace falta un tipo de font?

en web se ve bien, pero si abres la pagina en tu celular, en inicio en "nuestro compromiso" veras como las a con acentos se ven diferente .. alguna idea?

pool sugiere dice esto:

-- El font seleccionado fue de google fonts y tiene acentos.
https://www.google.com/fonts/specimen/Questrial

Si no funciona puedes reemplazar titulos por MULI: 
https://www.google.com/fonts/specimen/Muli

**Comment by alex-romanov** [comment]
El font está piratón, te awitas si reemplazo todas las instancias de ese font por Muli?

**Comment by garciadiazjaime** [comment]
dale, la idea es que no se ve pirata

**Comment by alex-romanov** [comment]
Estoy seguro que  es que es algo que tiene que ver con la manera en que se renderean los acentos cuando se alimentan desde la BD.

Mi hipótesis es que tiene algo que ver con el momento específico en que se carga, o quizas la manera en que se parsean.
