### ISSUE TITLE
rd :: home :: nosotros

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#59]
no se ve "contemporaneo"

![screen shot 2016-05-23 at 8 48 09 pm](https://cloud.githubusercontent.com/assets/7799215/15489695/acdb329c-2127-11e6-9a0d-cde34f0f1f99.png)

**Comment by alex-romanov** [comment]
Done

**Comment by garciadiazjaime** [comment]
me sigue saliendo cortado
<img width="458" alt="screen shot 2016-05-25 at 1 49 47 pm" src="https://cloud.githubusercontent.com/assets/7799215/15552348/955129e8-227f-11e6-9e54-2f5e59175457.png">

**Comment by alex-romanov** [comment]
done again, lo había basado en el iphone 6
