### ISSUE TITLE
contacto :: mapa :: boton

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#62]
aparentemente esto pasa con todos los links, que al darles click se quedan como en el printscreen, supongo bootstrap tiene una clase de 'visited' o algo asi, la podemos sobre-escribir para que no se vean así?

![screen shot 2016-05-24 at 9 09 50 am](https://cloud.githubusercontent.com/assets/7799215/15507042/8dc3b290-218f-11e6-9b17-adb0343bcb72.png)

**Comment by alex-romanov** [comment]
done

**Comment by garciadiazjaime** [comment]
esto tambien pasa con el llink que esta dentro del texto

<img width="344" alt="screen shot 2016-05-25 at 2 05 38 pm" src="https://cloud.githubusercontent.com/assets/7799215/15552821/d6b1d7dc-2281-11e6-94ab-614fcd86a76e.png">

**Comment by alex-romanov** [comment]
listo
