### ISSUE TITLE
productos :: producto :: agregar boton

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#63]
En la pagina de PRODUCTOS debajo de cada producto vamos a agregar un boton de  "DESCARGAR CATÁLOGO (arrow_down)"

El botón DESCARGAR CATALOGO (arrow_down)  lo podemos poner debajo del botón de CONTACTO, usando el mismo estilo.

Esto afectaría a las 3 categorías, todos los productos

![screen shot 2016-05-24 at 9 24 29 am](https://cloud.githubusercontent.com/assets/7799215/15507503/7c1d759c-2191-11e6-96cf-6cfe1593e56d.png)

**Comment by alex-romanov** [comment]
Done, pero el texto "descargar catálogo" está hardcoded

**Comment by alex-romanov** [comment]
done
