### ISSUE TITLE
servicios :: banner :: convertir a slider

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#64]
Podemos convertir esta imagen en un slider de imagenes para incluir las otras dos, cambiando automaticamente cada 5 seg.  con efecto push.  

images: https://basecamp.com/1879563/projects/12030021/todos/253129510

**Comment by alex-romanov** [comment]
Este cambio también va a ser para servicios (que ahorita es el mismo bloque o va a cambiar?)

**Comment by garciadiazjaime** [comment]
ya hice el cambio de img a slider, solo de momento no se muestra el slider, me parece hace falta especificar la altura, puedes revisar? (necesitaras hacer pull)

**Comment by alex-romanov** [comment]
Hice el pull pero no me sale el carousel, u sure is up there?

**Comment by garciadiazjaime** [comment]
de momento no se ve, pero si revisas el html ahi esta, fue hasta que le puse height que lo pude ver ... si te sale?

**Comment by alex-romanov** [comment]
Ya la encontré, me fuí con la finta de que el título dice "banner", it is not a banner, i'm on it.

**Comment by alex-romanov** [comment]
listo
