### ISSUE TITLE
rd :: home :: slider

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#68]
el contenido de los tres slides no sale centrado, sale como jalado a la derecha, se puede hacer algo?
<img width="451" alt="screen shot 2016-05-25 at 1 49 00 pm" src="https://cloud.githubusercontent.com/assets/7799215/15552332/816ca06a-227f-11e6-88cb-76c851194049.png">

**Comment by alex-romanov** [comment]
sip, it's fixed
