### ISSUE TITLE
productos :: showroom :: carousel

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#73]
- Anteriormente teniamos una img, ahora es un slider, tiene algunos detalles como las fechas que estan arriba en lugar de centradas verticalmente, y un rollo con alto, me parece lo puedes ver facilmente.

<img width="550" alt="screen shot 2016-06-14 at 6 09 35 pm" src="https://cloud.githubusercontent.com/assets/7799215/16062795/2b460974-325b-11e6-89e4-53f117df468c.png">

[showroom]
http://www.notable.mx/productos

**Comment by alex-romanov** [comment]
done
