### ISSUE TITLE
rd :: servicios :: slider

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-notable#74]
las fotos del slider tienen el detalle del enfoque, ver si se puede mejorar con css, supondria que si pues las imgs en si no son tan grandes, por otra parte darle algo de padding-top para separar las imgs del boton de contactanos.

<img width="454" alt="screen shot 2016-06-14 at 6 10 37 pm" src="https://cloud.githubusercontent.com/assets/7799215/16062833/7699c294-325b-11e6-89a5-5dc5adbae5bf.png">

http://www.notable.mx/servicios

**Comment by alex-romanov** [comment]
done
